language: node_js
node_js:
- '7'
script:
- ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
- email: false
